# -*- coding: utf-8 -*-
"""01_TF2_MNIST_test_beginner_sparse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_bDzUvMHToW3LDypRjmDW5wV-RZgZkJW

# MNIST

아래의 code는 google colab 에서 시험된 결과이다.
Anaconda 에서 제공되는 jupyter notebook에서는 작동이 안될수 있다.
추천하는 방법은 notebook이 아니라 python 파일 자체를 실행하라는 것이다. TPU 예제만 빼고는 anaconda prompt 에서 *.py 파일을 실행하는 방법을 추천한다.
"""

import tensorflow as tf

"""Tensorflow2 에서는 아래와 같이 MNIST 데이터를 부를수 있다. 
" sparse_categorical_crossentropy "를 사용하기 위하여 는 Y_Train/Y_test 값을 10개정도 출력시켜 보자.

"""

mnist = tf.keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

print(Y_train[0:10])

"""아래에서는 loss 가 "sparse_categorical_crossentropy"를 사용하고 있음을 주의하자.
이는 위에서 사용된 Y_train/Y_test가 값으로 지정되기 때문이다.
"""

# sys.exit()

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=5, verbose=1)

model.evaluate(X_test,  Y_test, verbose=2)

""""verbose" 값에 따른 출력의 형태를 알아보면 아래와 같다.

verbose default is 1

verbose=0 (silent)

verbose=1 (progress bar)

Train on 186219 samples, validate on 20691 samples
Epoch 1/2
186219/186219 [==============================] - 85s 455us/step - loss: 0.5815 - acc: 
0.7728 - val_loss: 0.4917 - val_acc: 0.8029
Train on 186219 samples, validate on 20691 samples
Epoch 2/2
186219/186219 [==============================] - 84s 451us/step - loss: 0.4921 - acc: 
0.8071 - val_loss: 0.4617 - val_acc: 0.8168


verbose=2 (one line per epoch)

Train on 186219 samples, validate on 20691 samples
Epoch 1/1
 - 88s - loss: 0.5746 - acc: 0.7753 - val_loss: 0.4816 - val_acc: 0.8075
Train on 186219 samples, validate on 20691 samples
Epoch 1/1
 - 88s - loss: 0.4880 - acc: 0.8076 - val_loss: 0.5199 - val_acc: 0.8046
"""